### ISSUE TITLE
BattleScribe Beta 2.02.00.294 Android

### ISSUE THREAD

**Issue by MAHurrocane** [BattleScribe/Pre-Release#15]
Bug - Error when selecting a roster.
So before this update I had a couple of roster with each one named with a unique title.
The bug happened when I clicked on a roster  with said custom name it brought up a error replying that it didn't exist. So I closed the app and reopened it to then see that the roster had removed it self from my lists.

**Comment by Jonskichov** [comment]
I think this was a one-off thing, I'm unable to reproduce the issue and haven't heard anyone experience the same thing. Thanks for the feedback anyway!
