### ISSUE TITLE
Issue when changing primary category

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Pre-Release#18]
When changing the primary category for an item, it will only show it under the original category it was set to show when the roster was opened. 

Example: Bloodcrushers are Battleline if a Skullmaster is general. It's in Other if not. When the roster loads, it's in Other by default, so it shows there. I add Skullmaster, click General, it disappears from Other and does not show up in Battleline. I then reload the roster, with general checked, and it will show in Battleline, but not Other if I uncheck General.

![image](https://user-images.githubusercontent.com/4388344/63304657-0cb19a80-c2a1-11e9-8777-be5cef2387d3.png)
![image](https://user-images.githubusercontent.com/4388344/63304672-1dfaa700-c2a1-11e9-8cb8-4a4f8af20035.png)

**Comment by cartag** [comment]
After reloading the roster I have some more info on what may be the case. In the next three screenshots, it is from a fresh load of the roster with General checked at initial rendering. The behavior it should show is having Bloodcrushers in Battleline, then in Other, then in Battleline. It's not loading into Battleline in the last screenshot. 
![image](https://user-images.githubusercontent.com/4388344/63304811-9b261c00-c2a1-11e9-9bba-7d23a682d7dc.png)

![image](https://user-images.githubusercontent.com/4388344/63304938-2b646100-c2a2-11e9-9e73-09df199d3c60.png)

![image](https://user-images.githubusercontent.com/4388344/63304950-3919e680-c2a2-11e9-9d30-75fda072b5aa.png)

Showing how the logic tree is for the categories, does it "un-set" the primary category after it sets it to Battleline when it starts the check to see if it should load it as Other?

**Comment by cartag** [comment]
Sorry for all the updates to this, but to help narrow it down, could it be in the area of where the program handles the refreshing of the available entries list vs where it initially loads the entries?

**Comment by Jonskichov** [comment]
No worries about the updates :)

Thanks to your help I got it sorted.

Fixed in build 127: https://github.com/BattleScribe/Pre-Release/issues/17#issuecomment-523261050
