### ISSUE TITLE
Show/Hide Issue

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Pre-Release#24]
Just installed 2.03.04, and am having a problem with linked IDs. 

This is set to check if a general is one of 9 models, and should hide the selection for General's Adjunct. 
![image](https://user-images.githubusercontent.com/4388344/67129380-c2269e80-f1bb-11e9-9594-3efe1273eb8a.png)

What it is instead doing is checking for any instances of the "General" SSE. If I mark any model as the General in the army, it hides the General's Adjunct item. 

![image](https://user-images.githubusercontent.com/4388344/67129462-ff8b2c00-f1bb-11e9-81fb-84aa2b97abe3.png)

![image](https://user-images.githubusercontent.com/4388344/67129471-05810d00-f1bc-11e9-9567-2a0b7faf85d9.png)

I set it to look for 9 hardcoded red circle IDs, but it's instead hiding if there are any references to the one in the blue circle, which is not hard coded. 
![image](https://user-images.githubusercontent.com/4388344/67129570-44af5e00-f1bc-11e9-84d0-80366751c243.png)

**Comment by Jonskichov** [comment]
@cartag Looks like it's because your conditions have the "shared" box checked, so they're firing based on the _shared_ general, not the individual linked generals.

Let me know if that fixes things. Otherwise can you attach the files here so I can take a look.

**Comment by cartag** [comment]
It does not affect it one way or another. It's not recognizing ANY General link without the Shared on. 

It is in the Cities of Sigmar, the two that I'm checking (one to show, one to hide, double the testing at once!) are General's Adjunct, and Honoured Retinue

**Comment by cartag** [comment]
[Age of Sigmar.zip](https://github.com/BattleScribe/Pre-Release/files/3747274/Age.of.Sigmar.zip)

**Comment by cartag** [comment]
The same logic (If equal to 1 selections in Roster of General link) is used in the Hammerers entry in the Cities of Sigmar file to set a primary category, so it works there. That should help narrow down where in the code it is.

**Comment by cartag** [comment]
Correction, it is NOT working when setting primary category. So it's not that it's in the show/hide, it's in how it processes a link to an SSE. This may possibly be a request now, if it would be possible to check if a particular link exists, instead of the end result. I'll go reprogram the file since it doesn't seem possible right now.
