### ISSUE TITLE
Show/Hide on linked entries still not working quite right

### ISSUE THREAD

**Issue by alphalas** [BattleScribe/Pre-Release#29]
It’s simple commissars should only have Voice of Command/show orders if they take a warlord trait, But it shows even when they don’t have said WLT
![1F4E120C-26C9-456E-AF10-77CA7303FB19](https://user-images.githubusercontent.com/15703066/78076130-d3cbbf00-7373-11ea-825e-965135109f0a.jpeg)
![8EFF5D62-C1A1-4CAA-9E66-5222623E03AA](https://user-images.githubusercontent.com/15703066/78076133-d4fcec00-7373-11ea-858f-ad05265bc327.jpeg)

**Comment by Jonskichov** [comment]
Fixed in build 150: https://github.com/BattleScribe/Pre-Release/issues/25#issuecomment-609459601
