### ISSUE TITLE
Adding CatalogueLink hangs Data Editor

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Pre-Release#3]
I'm using current master of 40k files.

I've copied whole folder into User/BS_BETA/data as required. When opening the first file, conversion took place. It could be probably enhanced, since it seemed like the app hanged. I expected it to update the files to the new format, so I wasn't exactly worried, but still, a loooong time non-repsonsive UI.

Then, I've opened and saved game system and two catalogues, just to be sure.

I've tried linking Necrons into Tau. I can add CatalogueLink entry, but after selecting a catalogue, the right view half-hangs. It doesn't actually select the catalogue, the tree view shows NO TARGET, and I selecting anything else on the tree doesn't change the details view - but there I can still use dropdowns and edit fields of this link.

BS v2.02.00.109.BETA

**Comment by GenWilhelm** [comment]
I experienced this attempting to use the drop-down list.
Manually entering the UID of the target catalogue appears to work without issue.

**Comment by Jonskichov** [comment]
Fixed in build 110: https://github.com/BattleScribe/Pre-Release/issues/1#issuecomment-397679417
