### ISSUE TITLE
Duplicating unit issue.

### ISSUE THREAD

**Issue by WikkedTiki** [BattleScribe/Pre-Release#30]
File/Catalogue: 40k Necrons v61

BattleScribe version: 2.03.15.148

Platform: Windows

Dropbox: No

Created a unit of 9 Tomblades with nebulascopes and shieldvanes. Clicked to duplicate the first bike, nothing happened. Manually entered the next 8 tomb blades for the unit. Duplicated the whole unit and it made 2 extra copies for the points cost of one. Tried it again, a single dupliacte created 2 extras for the price of one.
image
![image](https://user-images.githubusercontent.com/29361456/78413680-c6157400-75d5-11ea-8224-d3a9b444a1cb.png)

**Comment by Jonskichov** [comment]
Fixed in https://github.com/BattleScribe/Pre-Release/issues/25#issuecomment-608931563
