### ISSUE TITLE
Build 151 Data Editor stops loading profile details

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Pre-Release#31]
Build 151 stops loading all profiles into the right pane if you do the following:-

1. Open a data file which contains a profile with a profile modifier which has conditions - e.g. 40k Chaos Space Marines - Shared Selection Entries -> Chaos Cultists -> Mere Mortals
1. Click on the profile and the profile details will load in the right pane.
1. Expand and then click on the modifier. The right pane does not properly load it.
1. The right pane no longer loads the details of any entry. It is doing something as it sometimes loads an icon in the pane.
![image](https://user-images.githubusercontent.com/29306451/78826224-11b28e00-79d9-11ea-8e7f-8f23a22f5517.png)

Profile modifiers which do not have modifiers do not exhibit this behaviour.

**Comment by Jonskichov** [comment]
Fixed in build 152: https://github.com/BattleScribe/Pre-Release/issues/25#issuecomment-614970659
