### ISSUE TITLE
Increment repeat not working

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Pre-Release#32]
https://github.com/BSData/wh40k/issues/6955

**Comment by Jonskichov** [comment]
Duplicate of https://github.com/BattleScribe/Pre-Release/issues/35

**Comment by GenWilhelm** [comment]
This was a different issue to the one in #35 

The issue linked in the OP is that the modified `Max in Parent` causes the fixed `Max in Parent` to no longer be a hard limit (i.e. the spinner control doesn't have a maximum value).
