### ISSUE TITLE
Minor missing features compared to Release version

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Pre-Release#34]
1. Adding a new entry doesn't focus on the entry.
1. Can't type to search in target boxes
1. Collective items are not listed as such in the left pane.
1. Can't delete entries with the Delete key because Name is always focused on selecting an entry.
1.  Follow Link sometimes put the selected item underneath the top panel.

**Comment by Jonskichov** [comment]
Fixed in build 152: https://github.com/BattleScribe/Pre-Release/issues/25#issuecomment-614970659
