### ISSUE TITLE
Minor bugs + feature request

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Pre-Release#35]
Bugs:
- Root Entry Links inherited from the GST lose their primary category in the roster editor, appearing as "Uncategorised".
- Repeating modifiers appear to have stopped resolving. Example: wh40k > Tyranids.cat > Genestealers > Scything Talons > max in parent constraint is always 0, regardless of number of selections of Genestealer.

Feature Request:
- Have separate icons for models and upgrades.

**Comment by Jonskichov** [comment]
Fixed in build 152: https://github.com/BattleScribe/Pre-Release/issues/25#issuecomment-614970659
