### ISSUE TITLE
Bug - Data Editor 2.02.00.119.BETA

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Pre-Release#9]
The (select) section of the Filter By box will not list Shared Entries or Groups after the Categories. 
![image](https://user-images.githubusercontent.com/4388344/55373196-a1b62180-54c1-11e9-8a80-9928e44c244d.png)

**Comment by Jonskichov** [comment]
Do they show up later in the list? Can you reference them by ID? (I probably won't get a chance to check for myself until tomorrow)

**Comment by cartag** [comment]
They don't show up at all. When referencing by ID they show temporarily then revert back to empty, as if it's not a valid selection.

**Comment by Jonskichov** [comment]
Definitely a bug. I'll get it sorted, thanks.

**Comment by Jonskichov** [comment]
Hm, I can see shared items in the dropdown. Can you give specifics of the catalogue, what entry / condition you're looking at and what shared item(s) you are unable to find in the dropdown?

**Comment by Jonskichov** [comment]
actually don't worry, this appears to be an issue with the current version too.

**Comment by Jonskichov** [comment]
Fixed in build 120: https://github.com/BattleScribe/Pre-Release/issues/1#issuecomment-480396467
